### ISSUE TITLE
Unable to seed db on Mac OSX

### ISSUE THREAD

**Issue by adamjbradley** [nov/openid_connect_sample_rp#9]
Could I grab your sqlite3  db so I can test (:

Environment is ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]. The following error is throw

---snip---
bundle exec rake --trace db:create db:migrate db:seed

** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke rails_env (first_time)
** Execute rails_env
** Execute db:create
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config 
** Execute db:migrate
==  CreateAccounts: migrating =================================================
-- create_table(:accounts)
   -> 0.0009s
==  CreateAccounts: migrated (0.0009s) ========================================

==  CreateOpenIds: migrating ==================================================
-- create_table(:open_ids)
   -> 0.0012s
==  CreateOpenIds: migrated (0.0013s) =========================================

==  CreateProviders: migrating ================================================
-- create_table(:providers)
   -> 0.0058s
==  CreateProviders: migrated (0.0059s) =======================================

** Invoke db:_dump (first_time)
** Execute db:_dump
** Invoke db:schema:dump (first_time)
** Invoke environment 
** Invoke db:load_config 
** Execute db:schema:dump
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment 
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
rake aborted!
TypeError: Cannot visit Integer
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:25:in `rescue in visit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:241:in `visit_Arel_Nodes_Limit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:123:in `visit_Arel_Nodes_SelectStatement'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/sqlite.rb:12:in `visit_Arel_Nodes_SelectStatement'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:5:in `accept'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:19:in `accept'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `to_sql'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_one'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:30:in `select_value'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/relation/finder_methods.rb:202:in `exists?'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations/uniqueness.rb:33:in `validate_each'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validator.rb:153:in `block in validate'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validator.rb:150:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validator.rb:150:in `validate'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:310:in `_callback_before_63'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:429:in `_run__1697114164217243228__validate__859568604122490323__callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:385:in `_run_validate_callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validations.rb:228:in `run_validations!'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validations/callbacks.rb:53:in `block in run_validations!'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:403:in `_run__1697114164217243228__validation__859568604122490323__callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:385:in `_run_validation_callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validations/callbacks.rb:53:in `run_validations!'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validations.rb:195:in `valid?'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:69:in `valid?'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:77:in `perform_validations'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:56:in `save!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:264:in `block in save!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:208:in `transaction'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:264:in `save!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:41:in `create!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:37:in `block in create!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:37:in `collect'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:37:in `create!'
/Users/abradley/Projects/Unify/B2C/Meeco/Ruby/openid_connect_sample_rp/db/seeds.rb:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/railties-3.2.22.5/lib/rails/engine.rb:525:in `load_seed'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/railties/databases.rake:347:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
NoMethodError: undefined method `visit_Integer' for #<Arel::Visitors::SQLite:0x007fde709f83b8>
Did you mean?  visit_String
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:241:in `visit_Arel_Nodes_Limit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:123:in `visit_Arel_Nodes_SelectStatement'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/sqlite.rb:12:in `visit_Arel_Nodes_SelectStatement'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:5:in `accept'
/usr/local/lib/ruby/gems/2.4.0/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:19:in `accept'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `to_sql'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_one'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:30:in `select_value'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/relation/finder_methods.rb:202:in `exists?'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations/uniqueness.rb:33:in `validate_each'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validator.rb:153:in `block in validate'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validator.rb:150:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validator.rb:150:in `validate'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:310:in `_callback_before_63'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:429:in `_run__1697114164217243228__validate__859568604122490323__callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:385:in `_run_validate_callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validations.rb:228:in `run_validations!'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validations/callbacks.rb:53:in `block in run_validations!'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:403:in `_run__1697114164217243228__validation__859568604122490323__callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:385:in `_run_validation_callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validations/callbacks.rb:53:in `run_validations!'
/usr/local/lib/ruby/gems/2.4.0/gems/activemodel-3.2.22.5/lib/active_model/validations.rb:195:in `valid?'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:69:in `valid?'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:77:in `perform_validations'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:56:in `save!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:264:in `block in save!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:208:in `transaction'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:264:in `save!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:41:in `create!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:37:in `block in create!'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:37:in `collect'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/validations.rb:37:in `create!'
/Users/abradley/Projects/Unify/B2C/Meeco/Ruby/openid_connect_sample_rp/db/seeds.rb:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/railties-3.2.22.5/lib/rails/engine.rb:525:in `load_seed'
/usr/local/lib/ruby/gems/2.4.0/gems/activerecord-3.2.22.5/lib/active_record/railties/databases.rake:347:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:seed

---snip---

Sincerely,
//Adam

**Comment by jnardone** [comment]
This is likely related to the ancient version of Rails used in the example.  (3.2 is nearly 6 years old, and is out of support.)  Running an earlier version of Ruby (2.3.3 is in the .ruby-version file) looks like it would work.

**Comment by joshuapinter** [comment]
You're correct @jnardone. Looks like the last version of Ruby that Rails 3.2.22.5 supports is Ruby 2.3.6.

After that, you'll need to update Rails to 4+.
